spring:
  application:
    name: cloud-config
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations:
            - classpath:/config
            - file:///D://config
server:
  port: 8088
  #spring.cloud.config.server.native.search-locations=classpath:/config
  #spring.cloud.config.server.native.search-locations=file:///D://config
